name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.3.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
  string_scanner: ^1.0.0
  path: ^1.5.1
  markdown:
    git: git://github.com/R65LabsInc/markdown.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

environment:
  sdk: '>=2.5.0 <3.0.0'

flutter:
  assets:
    - assets/logo.png
